### ISSUE TITLE
Roadmap: workflows support for sparse tibbles

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/workflows#239]
What we need:

- [x] `fit()` to take sparse tibbles as data https://github.com/tidymodels/workflows/pull/245
- [x] `fit()` to take {Matrix} sparse matrix as data https://github.com/tidymodels/workflows/pull/258
  - turn them into sparse tibbles early
- [x] `predict()` to take sparse tibbles as data https://github.com/tidymodels/workflows/pull/261
- [x] `predict()` to take {Matrix} sparse matrix as data https://github.com/tidymodels/workflows/pull/261
  - turn them into sparse tibbles early

Adding all of this will give us:
- everything it needs to be able to work with the rest of {tidymodels} in regards to sparse tibbles
